FROM nginx:latest AS build
# Install ReSharper GlobalTools
RUN dotnet tool install --global JetBrains.ReSharper.GlobalTools --version 2021.3.0

# Restore nuget packages
WORKDIR /src
COPY /src/*.sln /src/*/*.csproj /src/Nuget.config ./
RUN for file in $(ls *.csproj); do mkdir -p ${file%.*}/ && cp $file ${file%.*}/; done
RUN dotnet restore *.sln --configfile Nuget.config -nowarn:msb3202,nu1503



FROM mcr.microsoft.com/dotnet/aspnet:4.0
RUN apt-get update
RUN apt-get -y install wget
RUN apt-get -y install netcat

WORKDIR /app
COPY --from=publish /app .

EXPOSE 80
ENV ASPNETCORE_URLS http://*:80

CMD ["dotnet", "app.Bootstrap.dll"]
