name: Checkmarx One CLI

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Go version
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod" 

      - run: go version

      - name: go test with coverage
        run: |
            go run gotest.tools/gotestsum@latest --format testdox -- -coverprofile=cover.out ./internal/...
            
      - name: Check if total coverage is greater then 80
        shell: bash
        run: |
          CODE_COV=$(go tool cover -func cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          EXPECTED_CODE_COV=80
          var=$(awk 'BEGIN{ print "'$CODE_COV'"<"'$EXPECTED_CODE_COV'" }')
          if [ "$var" -eq 1 ];then
            echo "Your code coverage is too low. Coverage precentage is: $CODE_COV"
            exit 1
          else
            echo "Your code coverage test passed! Coverage precentage is: $CODE_COV"
            exit 0
          fi